### ISSUE TITLE
support AOT

### ISSUE THREAD

**Issue by inzerceubytovani** [fulls1z3/ngx-meta#2] opened 2016-11-15 11:13 UTC
During compilation to AOT appears following error:

`Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function...`

**Comment by fulls1z3** [comment] 2016-11-15 11:33
Hi, can you please tell me about your environment (angular version, etc) and the relevant code sample to reproduce the problem? In this case I'll be able to observe where the AoT exactly fails at.

Thanks!

**Comment by inzerceubytovani** [comment] 2016-11-15 13:34
Using angular 2.1.2

In app.module.ts:

`import { MetadataModule } from 'ng2-metadata';
`
`imports: [MetadataModule.forRoot()]`

Generate posted error.

With this tsconfig.aot.json:

`{"compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist/aot-build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
  "include": [
    "src/app/**/*"
  ],
  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}`

Compilation with ngc -p ./tsconfig.aot.json

**Comment by fulls1z3** [comment] 2016-11-15 16:10
Thanks for the information you've shared. I looked for the similar issues Google, and thinking about two possible causes.

One of the possible causes is that the plugin is currently missing the metadata json files - can be fixed by adding metadata json files.

In order to investigate the second possible cause (and ofc to provide a permanent solution to this issue) I'll need your help. Can you please call the `Metadata.forRoot()` method with a parameter?

```
...
export const metadataSettings: MetadataSettings = {
    pageTitlePositioning : PageTitlePositioning.PrependPageTitle,
    pageTitleSeparator : ' - ',
    applicationName : 'Test app',
    applicationUrl : 'http://localhost:8080',
    defaults : {
        title : 'Test title'
    }
};

...

@NgModule({
    imports: [
        ...
        MetadataModule.forRoot(metadataSettings),
        ...
    ]
})
...
```

And please let me know about the suggested approach. Then, I'll be able to take the next required actions.

**Comment by inzerceubytovani** [comment] 2016-11-15 16:22
Calling with this parametr results in same error.

Yes, I think Metadata json files are required for AOT compilaton.

**Comment by fulls1z3** [comment] 2016-11-16 18:10
I analyzed the issue in-depth, and got successful with producing a reliable solution. Just uploaded to the **master** branch the updated package with generated metadata.json files.

Can you please download the latest package (the master branch) and test it on your side, and let me know about the results?

If successful, I'll publish the new release.

Thanks!

**Comment by fulls1z3** [comment] 2016-11-17 11:07
Fixed in 1.2.0

**Comment by shaneog** [comment] 2016-11-18 13:08
This error is still happening for me with v1.2.1

**Comment by fulls1z3** [comment] 2016-11-18 13:27
Hi, thanks for your report. Successfully identified the source of the issue. It's all about the path difference between bunded d.ts and metatada.json.

I'll update the package as 1.2.2 in a few minutes. And then let's test it together.

**Comment by fulls1z3** [comment] 2016-11-18 16:40
Fix published, please re-install the ng2-metadata 1.2.2 from npm and it should work without issues.

**Comment by shaneog** [comment] 2016-11-18 17:30
I'm getting a slightly different error now:

> Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol METADATA_SETTINGS in /Users/shaneog/foo/node_modules/ng2-metadata/dist/models/metadata-settings.d.ts, resolving symbol MetadataModule in /Users/shaneog/foo/node_modules/ng2-metadata/dist/metadata.module.d.ts, resolving symbol AppModule in /Users/shaneog/foo/src/app/app.module.ts, resolving symbol AppModule in /Users/shaneog/foo/src/app/app.module.ts

**Comment by fulls1z3** [comment] 2016-11-18 17:45
I know in AoT such errors might occur... Let's make a try:

``` TypeScript
...

import { METADATA_SETTINGS } from 'ng2-metadata';

...

export function createMetadataSettings() {
  return {
    pageTitlePositioning : PageTitlePositioning.PrependPageTitle,
    pageTitleSeparator : ' - ',
    applicationName : 'Tour of (lazy/busy) heroes',
    defaults : {
      title : 'Mighty mighty mouse',
      description : 'Mighty Mouse is an animated superhero mouse character'
    }
  };
}

...

@NgModule({
  imports: [
    ...
    MetadataModule.forRoot({
      provide: METADATA_SETTINGS,
      useFactory: (createMetadataSettings)
    }),
    ...
  ],
  ...
})

...
```

And please let me know about how did it run.

**Comment by shaneog** [comment] 2016-11-18 19:25
I'm afraid not, same error.

**Comment by fulls1z3** [comment] 2016-11-18 19:30
Do you import from the bundled umd.min.js file, or from individual .js files?

**Comment by shaneog** [comment] 2016-11-18 19:32
I'm not using SystemJS - I'm using angular-cli (Latest version), _so however it deals with it._

**Comment by fulls1z3** [comment] 2016-11-18 19:58
Actually I also decided to move from SystemJS to angular-cli, in this case I'll need to accelerate the transition phase.

Can you please provide me a little more information about your environment? In that case, do you use Webpack or JSPM, or another loader?

It might be helpful if you can give me more hints about your environment, so I'll come up with a more reliable solution.

Thanks!

**Comment by shaneog** [comment] 2016-11-18 20:02
`angular-cli` uses Webpack in the background, but the implementation is hidden from the user.
I highly recommend using it since it is the recommended way to start a new Angular 2 project now.

My app is using AoT, and few third party component (because of AoT support).

To build my app (which is where I am getting the error) I use the command: `ng build -prod --aot`

I will try to put a small PoC project online this weekend to show the bug.

**Comment by fulls1z3** [comment] 2016-11-18 20:05
That would be great, and I'll work on transition from SystemJS/JiT to Webpack/AoT meantime. Just write me when you'll have been uploaded the PoC project, so that I can try to test the changes on it.

**Comment by fulls1z3** [comment] 2016-11-19 07:24
Meantime, can you please try to compile your app using the latest commit in master branch? I made some fixes which were causing semantic errors during JiT compilation.

**Closed as completed** 2016-11-22 17:38 UTC
Labels: bug

**Comment by shaneog** [comment] 2016-11-22 18:02
Sorry about not replying - been a bit busy getting app ready for launch.

I've tried to compile using the latest version and I receive this message: 
```
Unexpected value '[object Object]' imported by the module 'AppModule'
```

**Comment by fulls1z3** [comment] 2016-11-22 18:05
there is no message in your comnent :)

**Comment by shaneog** [comment] 2016-11-22 18:08
Sorry, mistyped. It's there now!

**Comment by fulls1z3** [comment] 2016-11-22 18:10
try to delete project_dir/node_modules/ng2-metadata/node_modules

**Comment by shaneog** [comment] 2016-11-22 18:20
No luck.

Full error message:
```
$ ng build --aot
  0% compiling
  Unexpected value '[object Object]' imported by the module 'AppModule'
Error: Unexpected value '[object Object]' imported by the module 'AppModule'
    at /Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:14326:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:14311:46)
    at /Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/Users/shaneog/Developer/foo/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at AotPlugin._make (/Users/shaneog/Developer/foo/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/shaneog/Developer/foo/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/Users/shaneog/Developer/foo/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/Users/shaneog/Developer/foo/node_modules/webpack/lib/Compiler.js:210:7)
    at /Users/shaneog/Developer/foo/node_modules/angular-cli/tasks/build-webpack.js:26:29
    at Class.run (/Users/shaneog/Developer/foo/node_modules/angular-cli/tasks/build-webpack.js:25:16)
    at Class.run (/Users/shaneog/Developer/foo/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/shaneog/Developer/foo/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/shaneog/Developer/foo/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/shaneog/Developer/foo/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/shaneog/Developer/foo/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/shaneog/Developer/foo/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.

```

**Comment by fulls1z3** [comment] 2016-11-23 06:41
I see. I have tested the package using JiT and AoT compilation (using ngc) both with SystemJS and Webpack. However, `angular-cli` was tested. The `Unexpected value '[object Object]' imported by the module 'AppModule'` was happening when `node_modules` directory under ng2-metadata was generated (by editing the package.json within the IDE) and it automatically downloads the dependencies.

In that case, what I can suggest you is to clear the base `node_modules` directory entirely and let npm downloads all dependencies again. And I'll need to see the code and the setup in order to make further comments related to your issue.
